//! User configuration: fonts, color scheme, shell profiles.
//!
//! Loaded from %APPDATA%\baduhan\settings.json. On first run the file is
//! generated by importing Windows Terminal's settings (profiles, default
//! font, color schemes — including dynamic-source profiles resolved via WT
//! fragment files) plus auto-detected shells (WSL distros, Git Bash, cmd).

#[allow(unused_imports)]
use std::path::{Path, PathBuf};

use alacritty_terminal::vte::ansi::Rgb;
use serde::{Deserialize, Serialize};

use crate::palette;

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Profile {
    pub name: String,
    /// argv: [exe, args...]. The exe may contain spaces (already resolved).
    pub command: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cwd: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SchemeConfig {
    pub foreground: String,
    pub background: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<String>,
    /// black, red, green, yellow, blue, magenta, cyan, white, then brights.
    pub ansi: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Config {
    #[serde(default = "default_font_family")]
    pub font_family: String,
    #[serde(default = "default_font_size")]
    pub font_size: f32,
    /// 0.0 disables; otherwise the opacity of the black veil drawn over
    /// inactive terminal panes (iTerm2-style split dimming).
    #[serde(default = "default_dim")]
    pub dim_inactive_panes: f32,
    /// Scrollback history per pane, in lines (primary screen only; the alt
    /// screen never scrolls back).
    #[serde(default = "default_scrollback")]
    pub scrollback_lines: usize,
    /// Chrome DevTools Protocol port for the embedded browser (Playwright's
    /// connectOverCDP, claude --chrome, etc.). 0 disables.
    #[serde(default = "default_cdp_port")]
    pub browser_debug_port: u16,
    /// Reopen last session's windows/tabs/splits (with cwds) on launch.
    #[serde(default = "default_true")]
    pub restore_session: bool,
    /// Global hotkey toggling the quake-style dropdown terminal
    /// (e.g. "ctrl+`", "win is not supported"; empty disables).
    #[serde(default = "default_quake_hotkey")]
    pub quake_hotkey: String,
    /// Alt keys to release back to the shell as Meta instead of the built-in
    /// Alt binding, e.g. ["d", "shift+d", "3"] frees M-d (kill-word) and
    /// Alt+3. Hot-reloads; the Ctrl+Shift equivalents keep working.
    #[serde(default)]
    pub alt_passthrough: Vec<String>,
    #[serde(default)]
    pub default_profile: String,
    #[serde(default)]
    pub profiles: Vec<Profile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub scheme: Option<SchemeConfig>,
    /// Name of the active theme from the themes dir (cycle position).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
}

fn default_font_family() -> String {
    "Cascadia Mono".into()
}
fn default_font_size() -> f32 {
    13.0
}
fn default_dim() -> f32 {
    0.22
}
fn default_scrollback() -> usize {
    10_000
}
fn default_cdp_port() -> u16 {
    9333
}
fn default_true() -> bool {
    true
}
fn default_quake_hotkey() -> String {
    "ctrl+`".into()
}

impl Default for Config {
    fn default() -> Self {
        Config {
            font_family: default_font_family(),
            font_size: default_font_size(),
            dim_inactive_panes: default_dim(),
            scrollback_lines: default_scrollback(),
            browser_debug_port: default_cdp_port(),
            restore_session: true,
            quake_hotkey: default_quake_hotkey(),
            alt_passthrough: Vec::new(),
            default_profile: String::new(),
            profiles: Vec::new(),
            scheme: None,
            theme: None,
        }
    }
}

impl Config {
    pub fn path() -> PathBuf {
        let base = std::env::var_os("APPDATA")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("."));
        base.join("baduhan").join("settings.json")
    }

    /// Load the config; on first run, build one from Windows Terminal +
    /// detected shells and write it out so the user has a file to edit.
    pub fn load_or_create() -> Config {
        let path = Self::path();
        if let Ok(text) = std::fs::read_to_string(&path) {
            match serde_json::from_str::<Config>(&strip_jsonc(&text)) {
                Ok(mut cfg) => {
                    cfg.ensure_profiles();
                    return cfg;
                },
                Err(e) => {
                    eprintln!("config parse error ({}): {e}", path.display());
                    // Fall through to defaults but DON'T overwrite the
                    // user's broken file.
                    let mut cfg = Config::default();
                    cfg.ensure_profiles();
                    return cfg;
                },
            }
        }
        let mut cfg = import_windows_terminal().unwrap_or_default();
        cfg.ensure_profiles();
        if let Some(dir) = path.parent() {
            let _ = std::fs::create_dir_all(dir);
        }
        if let Ok(json) = serde_json::to_string_pretty(&cfg) {
            let _ = std::fs::write(&path, json);
        }
        cfg
    }

    /// Guarantee at least one working profile and a valid default.
    fn ensure_profiles(&mut self) {
        if self.profiles.is_empty() {
            self.profiles = detect_shells();
        }
        if self.profiles.is_empty() {
            self.profiles.push(Profile {
                name: "PowerShell".into(),
                command: vec!["powershell.exe".into()],
                cwd: None,
            });
        }
        if !self.profiles.iter().any(|p| p.name == self.default_profile) {
            self.default_profile = self.profiles[0].name.clone();
        }
    }

    pub fn default_profile(&self) -> &Profile {
        self.profiles
            .iter()
            .find(|p| p.name == self.default_profile)
            .unwrap_or(&self.profiles[0])
    }

    pub fn scheme(&self) -> palette::Scheme {
        let mut s = palette::Scheme::campbell();
        let Some(sc) = &self.scheme else { return s };
        if let Some(c) = parse_hex(&sc.foreground) {
            s.fg = c;
        }
        if let Some(c) = parse_hex(&sc.background) {
            s.bg = c;
        }
        s.cursor = sc.cursor.as_deref().and_then(parse_hex).unwrap_or(s.fg);
        for (i, hex) in sc.ansi.iter().take(16).enumerate() {
            if let Some(c) = parse_hex(hex) {
                s.ansi[i] = c;
            }
        }
        s
    }
}

impl Config {
    /// Persist the current config (pretty JSON, no BOM).
    pub fn save(&self) -> std::io::Result<()> {
        let path = Self::path();
        if let Some(dir) = path.parent() {
            std::fs::create_dir_all(dir)?;
        }
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
        std::fs::write(path, json)
    }
}

pub fn hex(c: Rgb) -> String {
    format!("#{:02X}{:02X}{:02X}", c.r, c.g, c.b)
}

/// Parse an iTerm2 .itermcolors file (XML plist): Ansi 0..15, Foreground,
/// Background, Cursor — each a dict of Red/Green/Blue Component reals.
pub fn parse_itermcolors(xml: &str) -> Option<SchemeConfig> {
    fn component(dict: &str, name: &str) -> Option<f32> {
        let key = format!("<key>{name} Component</key>");
        let at = dict.find(&key)? + key.len();
        let rest = &dict[at..];
        let start = rest.find("<real>")? + 6;
        let end = rest[start..].find("</real>")? + start;
        rest[start..end].trim().parse().ok()
    }
    fn to_hex(dict: &str) -> Option<String> {
        let f = |v: f32| (v.clamp(0.0, 1.0) * 255.0).round() as u8;
        let (r, g, b) = (
            component(dict, "Red")?,
            component(dict, "Green")?,
            component(dict, "Blue")?,
        );
        Some(hex(Rgb { r: f(r), g: f(g), b: f(b) }))
    }

    let mut ansi: Vec<Option<String>> = vec![None; 16];
    let mut fg = None;
    let mut bg = None;
    let mut cursor = None;
    let mut i = 0;
    while let Some(k) = xml[i..].find("<key>") {
        let kstart = i + k + 5;
        let Some(kend) = xml[kstart..].find("</key>") else { break };
        let name = xml[kstart..kstart + kend].trim().to_string();
        let after = kstart + kend + 6;
        if name.ends_with("Color") {
            let Some(dend) = xml[after..].find("</dict>") else { break };
            let dict = &xml[after..after + dend];
            let value = to_hex(dict);
            if let Some(v) = value {
                if let Some(n) = name.strip_prefix("Ansi ").and_then(|s| {
                    s.strip_suffix(" Color").and_then(|n| n.parse::<usize>().ok())
                }) {
                    if n < 16 {
                        ansi[n] = Some(v);
                    }
                } else {
                    match name.as_str() {
                        "Foreground Color" => fg = Some(v),
                        "Background Color" => bg = Some(v),
                        "Cursor Color" => cursor = Some(v),
                        _ => {},
                    }
                }
            }
            i = after + dend + 7;
        } else {
            i = after;
        }
    }
    let ansi: Vec<String> = ansi.into_iter().flatten().collect();
    if ansi.len() != 16 {
        return None;
    }
    Some(SchemeConfig { foreground: fg?, background: bg?, cursor, ansi })
}

/// Parse a Windows Terminal-style scheme json fragment
/// ({"name", "black", ..., "foreground", "background", "cursorColor"}).
pub fn parse_wt_scheme(json: &str) -> Option<SchemeConfig> {
    let v: serde_json::Value = serde_json::from_str(&strip_jsonc(json)).ok()?;
    let c = |key: &str| v.get(key).and_then(|x| x.as_str()).map(String::from);
    let ansi_keys = [
        "black", "red", "green", "yellow", "blue", "purple", "cyan", "white",
        "brightBlack", "brightRed", "brightGreen", "brightYellow", "brightBlue",
        "brightPurple", "brightCyan", "brightWhite",
    ];
    let ansi: Vec<String> = ansi_keys.iter().filter_map(|k| c(k)).collect();
    if ansi.len() != 16 {
        return None;
    }
    Some(SchemeConfig {
        foreground: c("foreground")?,
        background: c("background")?,
        cursor: c("cursorColor"),
        ansi,
    })
}

/// %APPDATA%\baduhan\themes — drop .json (WT scheme) or .itermcolors files
/// here; Ctrl+Shift+S cycles through them.
pub fn themes_dir() -> PathBuf {
    Config::path().with_file_name("themes")
}

/// Theme files, sorted by name: (display name, path).
pub fn list_themes() -> Vec<(String, PathBuf)> {
    let mut out: Vec<(String, PathBuf)> = std::fs::read_dir(themes_dir())
        .into_iter()
        .flatten()
        .flatten()
        .filter_map(|e| {
            let p = e.path();
            let ext = p.extension()?.to_string_lossy().to_lowercase();
            if ext != "json" && ext != "itermcolors" {
                return None;
            }
            Some((p.file_stem()?.to_string_lossy().into_owned(), p))
        })
        .collect();
    out.sort_by_key(|a| a.0.to_lowercase());
    out
}

pub fn load_theme_file(path: &Path) -> Option<SchemeConfig> {
    let text = std::fs::read_to_string(path).ok()?;
    if text.trim_start_matches('\u{feff}').trim_start().starts_with('{') {
        parse_wt_scheme(&text)
    } else {
        parse_itermcolors(&text)
    }
}

pub fn parse_hex(s: &str) -> Option<Rgb> {
    let s = s.trim().trim_start_matches('#');
    if s.len() != 6 {
        return None;
    }
    let v = u32::from_str_radix(s, 16).ok()?;
    Some(Rgb { r: (v >> 16) as u8, g: (v >> 8) as u8, b: v as u8 })
}

// ----- shell detection -------------------------------------------------------

/// Build profiles for everything we can find on this machine.
pub fn detect_shells() -> Vec<Profile> {
    let mut out = Vec::new();
    if let Some(p) = find_on_path("pwsh.exe") {
        out.push(Profile { name: "PowerShell 7".into(), command: vec![p], cwd: None });
    }
    out.push(Profile {
        name: "Windows PowerShell".into(),
        command: vec![expand_env("%SystemRoot%\\System32\\WindowsPowerShell\\v1.0\\powershell.exe")],
        cwd: None,
    });
    out.push(Profile {
        name: "Command Prompt".into(),
        command: vec![expand_env("%SystemRoot%\\System32\\cmd.exe")],
        cwd: None,
    });
    for exe in ["C:\\Program Files\\Git\\bin\\bash.exe", "C:\\Program Files (x86)\\Git\\bin\\bash.exe"] {
        if Path::new(exe).is_file() {
            out.push(Profile {
                name: "Git Bash".into(),
                command: vec![exe.into(), "-i".into(), "-l".into()],
                cwd: None,
            });
            break;
        }
    }
    for distro in wsl_distros() {
        out.push(Profile {
            name: distro.clone(),
            command: vec!["wsl.exe".into(), "-d".into(), distro, "--cd".into(), "~".into()],
            cwd: None,
        });
    }
    out
}

fn find_on_path(exe: &str) -> Option<String> {
    let path = std::env::var("PATH").ok()?;
    for dir in path.split(';') {
        let p = Path::new(dir.trim()).join(exe);
        if p.is_file() {
            return Some(p.to_string_lossy().into_owned());
        }
    }
    None
}

/// Registered WSL distros, default first (registry; no `wsl -l` subprocess —
/// its UTF-16 output and slow startup aren't worth it).
fn wsl_distros() -> Vec<String> {
    use windows::core::HSTRING;
    use windows::Win32::System::Registry::*;
    let mut out = Vec::new();
    unsafe {
        let mut lxss = HKEY::default();
        let sub = HSTRING::from("Software\\Microsoft\\Windows\\CurrentVersion\\Lxss");
        if RegOpenKeyExW(HKEY_CURRENT_USER, &sub, None, KEY_READ, &mut lxss).is_err() {
            return out;
        }
        let default_guid = reg_string(lxss, "DefaultDistribution");
        let mut i = 0u32;
        loop {
            let mut name = [0u16; 256];
            let mut len = name.len() as u32;
            if RegEnumKeyExW(
                lxss,
                i,
                Some(windows::core::PWSTR(name.as_mut_ptr())),
                &mut len,
                None,
                None,
                None,
                None,
            )
            .is_err()
            {
                break;
            }
            i += 1;
            let guid = String::from_utf16_lossy(&name[..len as usize]);
            let mut sub = HKEY::default();
            let subname = HSTRING::from(guid.clone());
            if RegOpenKeyExW(lxss, &subname, None, KEY_READ, &mut sub).is_ok() {
                if let Some(distro) = reg_string(sub, "DistributionName") {
                    // Docker plumbing distros aren't shells.
                    if !distro.starts_with("docker-desktop") {
                        if Some(&guid) == default_guid.as_ref() {
                            out.insert(0, distro);
                        } else {
                            out.push(distro);
                        }
                    }
                }
                let _ = RegCloseKey(sub);
            }
        }
        let _ = RegCloseKey(lxss);
    }
    out
}

fn reg_string(key: windows::Win32::System::Registry::HKEY, value: &str) -> Option<String> {
    use windows::core::HSTRING;
    use windows::Win32::System::Registry::*;
    unsafe {
        let name = HSTRING::from(value);
        let mut buf = [0u16; 512];
        let mut len = (buf.len() * 2) as u32;
        let mut kind = REG_VALUE_TYPE::default();
        if RegQueryValueExW(
            key,
            &name,
            None,
            Some(&mut kind),
            Some(buf.as_mut_ptr() as *mut u8),
            Some(&mut len),
        )
        .is_ok()
            && kind == REG_SZ
        {
            let n = (len as usize / 2).saturating_sub(1);
            return Some(String::from_utf16_lossy(&buf[..n]));
        }
    }
    None
}

// ----- Windows Terminal import ----------------------------------------------

/// Import font, schemes, and profiles from Windows Terminal's settings.json.
pub fn import_windows_terminal() -> Option<Config> {
    let local = std::env::var_os("LOCALAPPDATA").map(PathBuf::from)?;
    let candidates = [
        local.join("Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json"),
        local.join("Packages\\Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe\\LocalState\\settings.json"),
        local.join("Microsoft\\Windows Terminal\\settings.json"),
    ];
    let path = candidates.iter().find(|p| p.is_file())?;
    let text = std::fs::read_to_string(path).ok()?;
    let root: serde_json::Value = serde_json::from_str(&strip_jsonc(&text)).ok()?;

    let mut cfg = Config::default();

    // Fragment profiles (Git for Windows etc.) referenced by guid.
    let fragments = load_fragments();

    let defaults = root.pointer("/profiles/defaults");
    if let Some(face) = defaults
        .and_then(|d| d.pointer("/font/face"))
        .and_then(|v| v.as_str())
    {
        cfg.font_family = face.to_string();
    }
    if let Some(size) = defaults
        .and_then(|d| d.pointer("/font/size"))
        .and_then(|v| v.as_f64())
    {
        cfg.font_size = size as f32;
    }

    let default_guid = root.get("defaultProfile").and_then(|v| v.as_str()).unwrap_or("");
    let mut default_scheme_name: Option<String> = defaults
        .and_then(|d| d.get("colorScheme"))
        .and_then(|v| v.as_str())
        .map(String::from);

    if let Some(list) = root.pointer("/profiles/list").and_then(|v| v.as_array()) {
        for p in list {
            if p.get("hidden").and_then(|v| v.as_bool()).unwrap_or(false) {
                continue;
            }
            let guid = p.get("guid").and_then(|v| v.as_str()).unwrap_or("");
            // Merge in the fragment entry for dynamic-source profiles.
            let frag = fragments.iter().find(|f| {
                f.get("guid").and_then(|v| v.as_str()) == Some(guid)
            });
            let get = |key: &str| -> Option<&serde_json::Value> {
                p.get(key).or_else(|| frag.and_then(|f| f.get(key)))
            };
            let name = get("name").and_then(|v| v.as_str()).unwrap_or("Profile").to_string();
            let source = p.get("source").and_then(|v| v.as_str()).unwrap_or("");

            let command = if let Some(cl) = get("commandline").and_then(|v| v.as_str()) {
                split_commandline(&expand_env(cl))
            } else if source == "Windows.Terminal.Wsl" {
                vec!["wsl.exe".into(), "-d".into(), name.clone(), "--cd".into(), "~".into()]
            } else {
                continue; // VS dev shells, Azure, etc. — no way to launch
            };
            if command.is_empty() {
                continue;
            }
            let cwd = get("startingDirectory")
                .and_then(|v| v.as_str())
                .map(expand_env)
                .filter(|s| !s.is_empty() && Path::new(s).is_dir());

            if guid == default_guid {
                cfg.default_profile = name.clone();
                if let Some(s) = p.get("colorScheme").and_then(|v| v.as_str()) {
                    default_scheme_name = Some(s.to_string());
                }
            }
            cfg.profiles.push(Profile { name, command, cwd });
        }
    }

    // Resolve the scheme by name against the file's schemes array.
    if let (Some(name), Some(schemes)) =
        (&default_scheme_name, root.get("schemes").and_then(|v| v.as_array()))
        && let Some(s) = schemes
            .iter()
            .find(|s| s.get("name").and_then(|v| v.as_str()) == Some(name))
    {
        let c = |key: &str| s.get(key).and_then(|v| v.as_str()).map(String::from);
        let ansi_keys = [
            "black", "red", "green", "yellow", "blue", "purple", "cyan", "white",
            "brightBlack", "brightRed", "brightGreen", "brightYellow", "brightBlue",
            "brightPurple", "brightCyan", "brightWhite",
        ];
        let ansi: Vec<String> = ansi_keys.iter().filter_map(|k| c(k)).collect();
        if let (Some(fg), Some(bg)) = (c("foreground"), c("background"))
            && ansi.len() == 16
        {
            cfg.scheme = Some(SchemeConfig {
                foreground: fg,
                background: bg,
                cursor: c("cursorColor"),
                ansi,
            });
        }
    }
    if cfg.scheme.is_none() {
        // Write the active (Campbell) scheme explicitly so the user can edit it.
        let s = palette::Scheme::campbell();
        cfg.scheme = Some(SchemeConfig {
            foreground: hex(s.fg),
            background: hex(s.bg),
            cursor: Some(hex(s.cursor)),
            ansi: s.ansi.iter().map(|c| hex(*c)).collect(),
        });
    }

    Some(cfg)
}

/// All profile entries from WT fragment extension files.
fn load_fragments() -> Vec<serde_json::Value> {
    let mut dirs = Vec::new();
    if let Some(pd) = std::env::var_os("ProgramData") {
        dirs.push(PathBuf::from(pd).join("Microsoft\\Windows Terminal\\Fragments"));
    }
    if let Some(la) = std::env::var_os("LOCALAPPDATA") {
        dirs.push(PathBuf::from(la).join("Microsoft\\Windows Terminal\\Fragments"));
    }
    let mut out = Vec::new();
    for dir in dirs {
        let Ok(apps) = std::fs::read_dir(&dir) else { continue };
        for app in apps.flatten() {
            let Ok(files) = std::fs::read_dir(app.path()) else { continue };
            for f in files.flatten() {
                if f.path().extension().is_some_and(|e| e == "json")
                    && let Ok(text) = std::fs::read_to_string(f.path())
                    && let Ok(v) = serde_json::from_str::<serde_json::Value>(&strip_jsonc(&text))
                    && let Some(profiles) = v.get("profiles").and_then(|p| p.as_array())
                {
                    out.extend(profiles.iter().cloned());
                }
            }
        }
    }
    out
}

// ----- commandline handling --------------------------------------------------

/// Expand %VAR% references (Windows Terminal style commandlines).
pub fn expand_env(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(start) = rest.find('%') {
        out.push_str(&rest[..start]);
        let after = &rest[start + 1..];
        match after.find('%') {
            Some(end) => {
                let var = &after[..end];
                match std::env::var(var) {
                    Ok(v) => out.push_str(&v),
                    Err(_) => {
                        out.push('%');
                        out.push_str(var);
                        out.push('%');
                    },
                }
                rest = &after[end + 1..];
            },
            None => {
                out.push('%');
                rest = after;
            },
        }
    }
    out.push_str(rest);
    out
}

/// Split a Windows commandline into argv. Handles quoted exes/args and the
/// CreateProcess rule for unquoted exe paths with spaces ("C:/Program
/// Files/Git/bin/bash.exe -i -l"): try successively longer space-delimited
/// prefixes until one names an existing file.
pub fn split_commandline(cl: &str) -> Vec<String> {
    // Quote-aware tokenization; remember which tokens were quoted.
    let mut tokens: Vec<(String, bool)> = Vec::new();
    let mut cur = String::new();
    let mut quoted = false;
    let mut in_quotes = false;
    for ch in cl.chars() {
        match ch {
            '"' => {
                in_quotes = !in_quotes;
                quoted = true;
            },
            c if c.is_whitespace() && !in_quotes => {
                if !cur.is_empty() || quoted {
                    tokens.push((std::mem::take(&mut cur), quoted));
                    quoted = false;
                }
            },
            c => cur.push(c),
        }
    }
    if !cur.is_empty() || quoted {
        tokens.push((cur, quoted));
    }
    if tokens.is_empty() {
        return Vec::new();
    }

    // Exe = first token, unless it's unquoted and a longer prefix of
    // unquoted tokens names a real file.
    let mut split_at = 1;
    if !tokens[0].1 && !Path::new(&tokens[0].0).is_file() {
        for n in 2..=tokens.len() {
            if tokens[..n].iter().any(|(_, q)| *q) {
                break;
            }
            let cand: String =
                tokens[..n].iter().map(|(t, _)| t.as_str()).collect::<Vec<_>>().join(" ");
            if Path::new(&cand).is_file() {
                split_at = n;
                break;
            }
        }
    }
    let exe: String =
        tokens[..split_at].iter().map(|(t, _)| t.as_str()).collect::<Vec<_>>().join(" ");
    let mut argv = vec![exe.replace('/', "\\")];
    argv.extend(tokens[split_at..].iter().map(|(t, _)| t.clone()));
    argv
}

/// Strip // and /* */ comments plus trailing commas so serde_json can parse
/// Windows Terminal's JSONC. Also tolerates a UTF-8 BOM (Notepad,
/// PowerShell's Set-Content, and friends love adding one).
pub fn strip_jsonc(text: &str) -> String {
    let bytes = text.trim_start_matches('\u{feff}').as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    let mut in_str = false;
    while i < bytes.len() {
        let b = bytes[i];
        if in_str {
            out.push(b);
            if b == b'\\' && i + 1 < bytes.len() {
                out.push(bytes[i + 1]);
                i += 2;
                continue;
            }
            if b == b'"' {
                in_str = false;
            }
            i += 1;
            continue;
        }
        match b {
            b'"' => {
                in_str = true;
                out.push(b);
                i += 1;
            },
            b'/' if i + 1 < bytes.len() && bytes[i + 1] == b'/' => {
                while i < bytes.len() && bytes[i] != b'\n' {
                    i += 1;
                }
            },
            b'/' if i + 1 < bytes.len() && bytes[i + 1] == b'*' => {
                i += 2;
                while i + 1 < bytes.len() && !(bytes[i] == b'*' && bytes[i + 1] == b'/') {
                    i += 1;
                }
                i = (i + 2).min(bytes.len());
            },
            b',' => {
                // Trailing comma? Look ahead past whitespace/comments for } or ].
                let mut j = i + 1;
                loop {
                    while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                        j += 1;
                    }
                    if j + 1 < bytes.len() && bytes[j] == b'/' && bytes[j + 1] == b'/' {
                        while j < bytes.len() && bytes[j] != b'\n' {
                            j += 1;
                        }
                        continue;
                    }
                    if j + 1 < bytes.len() && bytes[j] == b'/' && bytes[j + 1] == b'*' {
                        j += 2;
                        while j + 1 < bytes.len() && !(bytes[j] == b'*' && bytes[j + 1] == b'/') {
                            j += 1;
                        }
                        j = (j + 2).min(bytes.len());
                        continue;
                    }
                    break;
                }
                if j < bytes.len() && (bytes[j] == b'}' || bytes[j] == b']') {
                    // Drop the comma.
                } else {
                    out.push(b);
                }
                i += 1;
            },
            _ => {
                out.push(b);
                i += 1;
            },
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strip_jsonc_tolerates_bom() {
        let src = "\u{feff}{\"a\": 1}";
        let v: serde_json::Value = serde_json::from_str(&strip_jsonc(src)).unwrap();
        assert_eq!(v["a"], 1);
    }

    #[test]
    fn strip_jsonc_comments_and_trailing_commas() {
        let src = r#"{
            // line comment
            "a": 1, /* block */ "b": [1, 2,],
            "c": "has // no comment, and a comma," ,
        }"#;
        let v: serde_json::Value = serde_json::from_str(&strip_jsonc(src)).unwrap();
        assert_eq!(v["a"], 1);
        assert_eq!(v["b"][1], 2);
        assert_eq!(v["c"], "has // no comment, and a comma,");
    }

    #[test]
    fn split_quoted_and_plain_commandlines() {
        assert_eq!(
            split_commandline(r#""C:\tools\my shell.exe" -a "b c""#),
            vec!["C:\\tools\\my shell.exe", "-a", "b c"]
        );
        assert_eq!(
            split_commandline("wsl.exe -d Ubuntu --cd ~"),
            vec!["wsl.exe", "-d", "Ubuntu", "--cd", "~"]
        );
    }

    #[test]
    fn split_unquoted_exe_with_spaces() {
        // Relies on Git for Windows being installed (true on this dev box);
        // fall back gracefully if it isn't.
        if Path::new("C:\\Program Files\\Git\\bin\\bash.exe").is_file() {
            assert_eq!(
                split_commandline("C:/Program Files/Git/bin/bash.exe -i -l"),
                vec!["C:\\Program Files\\Git\\bin\\bash.exe", "-i", "-l"]
            );
        }
    }

    #[test]
    fn expand_env_vars() {
        unsafe { std::env::set_var("BADUHAN_TEST_VAR", "xyz") };
        assert_eq!(expand_env("a %BADUHAN_TEST_VAR% b"), "a xyz b");
        assert_eq!(expand_env("%NOPE_NOT_SET_123%"), "%NOPE_NOT_SET_123%");
        assert_eq!(expand_env("50%"), "50%");
    }

    #[test]
    fn itermcolors_parsing() {
        // Minimal two-entry sample in real .itermcolors shape; pad the rest.
        let mut xml = String::from("<plist><dict>");
        for i in 0..16 {
            xml.push_str(&format!(
                "<key>Ansi {i} Color</key><dict>\
                 <key>Alpha Component</key><real>1</real>\
                 <key>Blue Component</key><real>{}</real>\
                 <key>Color Space</key><string>sRGB</string>\
                 <key>Green Component</key><real>0.5</real>\
                 <key>Red Component</key><real>0</real></dict>",
                i as f32 / 15.0
            ));
        }
        xml.push_str(
            "<key>Foreground Color</key><dict>\
             <key>Red Component</key><real>1</real>\
             <key>Green Component</key><real>1</real>\
             <key>Blue Component</key><real>1</real></dict>\
             <key>Background Color</key><dict>\
             <key>Red Component</key><real>0.05</real>\
             <key>Green Component</key><real>0.05</real>\
             <key>Blue Component</key><real>0.1</real></dict></dict></plist>",
        );
        let s = parse_itermcolors(&xml).expect("parse");
        assert_eq!(s.foreground, "#FFFFFF");
        assert_eq!(s.background, "#0D0D1A");
        assert_eq!(s.ansi.len(), 16);
        assert_eq!(s.ansi[0], "#008000"); // r=0 g=.5 b=0
        assert_eq!(s.ansi[15], "#0080FF"); // b=1.0
        assert!(parse_itermcolors("<plist></plist>").is_none());
    }

    #[test]
    fn wt_scheme_parsing() {
        let json = r##"{
            "name": "Test", "foreground": "#AAAAAA", "background": "#111111",
            "cursorColor": "#FF0000",
            "black": "#000000", "red": "#cc0000", "green": "#00cc00",
            "yellow": "#cccc00", "blue": "#0000cc", "purple": "#cc00cc",
            "cyan": "#00cccc", "white": "#cccccc", "brightBlack": "#666666",
            "brightRed": "#ff0000", "brightGreen": "#00ff00",
            "brightYellow": "#ffff00", "brightBlue": "#0000ff",
            "brightPurple": "#ff00ff", "brightCyan": "#00ffff",
            "brightWhite": "#ffffff"
        }"##;
        let s = parse_wt_scheme(json).expect("parse");
        assert_eq!(s.background, "#111111");
        assert_eq!(s.cursor.as_deref(), Some("#FF0000"));
        assert!(parse_wt_scheme("{}").is_none());
    }

    #[test]
    fn hex_roundtrip() {
        assert_eq!(parse_hex("#0C0C14"), Some(Rgb { r: 0x0C, g: 0x0C, b: 0x14 }));
        assert_eq!(parse_hex("ffffff"), Some(Rgb { r: 255, g: 255, b: 255 }));
        assert_eq!(parse_hex("#fff"), None);
    }
}
